# Generated by Django 5.0.1 on 2024-02-02 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medical_stuff_images/nurse_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse_app.nurse')),
            ],
        ),
    ]
