# Generated by Django 5.0.1 on 2024-03-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
