# Generated by Django 5.0.1 on 2024-02-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_app', '0002_nurseimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseimage',
            old_name='Nurse',
            new_name='nurse',
        ),
    ]
