# Generated by Django 5.0.10 on 2025-01-14 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0002_patientmedicalinfo_medicalnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalnotes',
            name='appointment_notes',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
