# Generated by Django 5.0.1 on 2024-02-02 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=255)),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.country')),
                ('provinces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.province')),
                ('towns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.town')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('hospitals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.medicalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('nrc', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('medical_history', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('prescription', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.diagnosis')),
                ('hospitals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.medicalinformation')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insurancecompany')),
                ('provinces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.province')),
                ('towns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.town')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patient_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.patient')),
            ],
        ),
    ]
