# Generated by Django 5.0.1 on 2024-02-22 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration_app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('insurance_app', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=255)),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.country')),
                ('provinces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.province')),
                ('towns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.town')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('hospitals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.medicalinformation')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('nrc', models.CharField(max_length=100)),
                ('patient_type', models.CharField(choices=[('OP', 'OUTWARD PATIENT'), ('IP', 'INWARD PATIENT')], max_length=3)),
                ('address', models.TextField()),
                ('medical_history', models.TextField()),
                ('blood_type', models.CharField(choices=[('A', 'BLOOD A'), ('B', 'BLOOD B'), ('O', 'BLOOD O')], max_length=1)),
                ('patient_unit', models.CharField(choices=[('U1', 'UNIT 1'), ('U2', 'UNIT 2'), ('U3', 'UNIT 3')], max_length=3)),
                ('treatment_plan', models.TextField()),
                ('prescription', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.country')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.diagnosis')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('hospitals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.medicalinformation')),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insurancecompany')),
                ('provinces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.province')),
                ('towns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.town')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/Medical_Stuff_Images/Patient_Images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.patient')),
            ],
        ),
    ]
