# Generated by Django 5.0.1 on 2024-02-02 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('A', 'BLOOD A'), ('B', 'BLOOD B'), ('O', 'BLOOD O')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
