# Generated by Django 5.0.1 on 2024-03-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='countries',
        ),
    ]
