# Generated by Django 5.0.1 on 2024-02-02 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_patient_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('OP', 'OUTWARD PATIENT'), ('IP', 'INWARD PATIENT')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_unit',
            field=models.CharField(choices=[('U1', 'UNIT 1'), ('U2', 'UNIT 2'), ('U3', 'UNIT 3')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
