# Generated by Django 5.0.1 on 2024-02-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('patient_app', '0003_patient_patient_type_patient_patient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
