# Generated by Django 5.0.1 on 2024-02-02 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinces', models.CharField(max_length=100)),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towns', models.CharField(max_length=100)),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.country')),
                ('provinces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.province')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('contact_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255)),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.country')),
                ('provinces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.province')),
                ('towns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.town')),
            ],
        ),
    ]
