# Generated by Django 5.0.1 on 2024-02-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('contact_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255)),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.country')),
                ('provinces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.province')),
                ('towns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration_app.town')),
            ],
        ),
    ]
