# Generated by Django 5.0.1 on 2024-02-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_alter_doctorimage_image_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
