# Generated by Django 5.0.1 on 2024-02-22 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('doctor_app', '0004_doctor_user_alter_doctorimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
